### ISSUE TITLE
Level 7 not working ok

### ISSUE THREAD

**Issue by franps** [kiksen1987/xpath-diner#4]
Correct answer is 
//orange[contains(@class,'small')]
but it doesnt work.

**Comment by ShykulaD** [comment]
No oranges and classes="small" on lvl 7

**Comment by franps** [comment]
![image](https://user-images.githubusercontent.com/4564591/61876359-0a873680-aec3-11e9-8cd1-95f917c3f05d.png)

I came back to check, yes, there are small oranges on lvl 7. But if you try to select them it says its wrong

**Comment by ShykulaD** [comment]
It seems that you have wrong game url
Try this one https://topswagcode.com/xpath/#
As you can see on this screenshot - https://take.ms/dVn47 - I don't have oranges and more lvl's are in my version

**Comment by franps** [comment]
I see, when I wrote the issue I was talking about this url: http://xpath.topswagcode.com/ where level 7 as the screenshot I sent. 
The url you sent has a different level 7

**Comment by ShykulaD** [comment]
Yeah, I see your point 😉
Play the game that I gave to you and it's better that your variant

**Comment by franps** [comment]
Great, thank you! Awesome game by the way!
